spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/testdb?statementInterceptors=com.yanci.MaskResultSetScannerInterceptor




mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yanci.dao

